<a href="https://colab.research.google.com/github/Sumant-crty/WinningSpaceRaceWithDataScience/blob/main/FoliumDashpot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install folium
!pip install pandas
import pandas as pd
import folium

Requirement already satisfied: folium in /usr/local/lib/python3.12/dist-packages (0.20.0)
Requirement already satisfied: branca>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from folium) (0.8.2)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.12/dist-packages (from folium) (3.1.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from folium) (2.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from folium) (2.32.4)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.12/dist-packages (from folium) (2025.11.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.9->folium) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->folium) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->folium) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->folium) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->folium) (2026.1.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
# Import folium MarkerCluster plugin
from folium.plugins import MarkerCluster
# Import folium MousePosition plugin
from folium.plugins import MousePosition
# Import folium DivIcon plugin
from folium.features import DivIcon

If you need to refresh your memory about folium, you may download and refer to this previous folium lab:

[Generating Maps with Python](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/labs/v4/DV0101EN-Exercise-Generating-Maps-in-Python.ipynb)

In [ ]:
## Task 1: Mark all launch sites on a map
# Initial the map
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)
# For each launch site, add a Circle object based on its coordinate (Lat, Long) values. In addition, add Launch site name as a popup label

for index, row in launch_sites_df.iterrows():
    # Create a circle for each launch site
    circle = folium.Circle(
        [row['Lat'], row['Long']],
        radius=1000, # Example radius, you can adjust this
        color='#008080', # Example color, you can choose another
        fill=True
    ).add_child(folium.Popup(row['Launch Site']))

    # Create a marker for each launch site with its name
    marker = folium.map.Marker(
        [row['Lat'], row['Long']],
        icon=DivIcon(
            icon_size=(20,20),
            icon_anchor=(0,0),
            html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % row['Launch Site'],
        )
    )

    site_map.add_child(circle)
    site_map.add_child(marker)

site_map

In [ ]:
# Download and read the `spacex_launch_geo.csv`
import requests
import io

URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'

# Use requests to get the content
resp = requests.get(URL)

# Read the content into a BytesIO object
spacex_csv_file = io.BytesIO(resp.content)

# Read the CSV file into a pandas DataFrame
spacex_df = pd.read_csv(spacex_csv_file)

In [ ]:
# Select relevant sub-columns: `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

In [ ]:
# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

In [ ]:
# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

## Task 2: Mark the success/failure of each launch on a map

Now, let's mark each launch attempt on the map. We will use `folium.CircleMarker` objects and color them based on the `class` column (0 for failure, 1 for success).

In [ ]:
# Create a new map centered on the mean coordinates (using nasa_coordinate as a general starting point)
launch_outcomes_map = folium.Map(location=nasa_coordinate, zoom_start=5)

# Iterate through each launch record in spacex_df
for index, row in spacex_df.iterrows():
    # Determine marker color based on 'class' column
    # Green for successful launches (class = 1)
    # Red for unsuccessful launches (class = 0)
    marker_color = 'green' if row['class'] == 1 else 'red'

    # Create a CircleMarker for each launch
    folium.CircleMarker(
        location=[row['Lat'], row['Long']],
        radius=5, # Small radius for individual launches
        color=marker_color,
        fill=True,
        fill_color=marker_color,
        fill_opacity=0.7,
        popup=f"Launch Site: {row['Launch Site']}<br>Outcome: {'Success' if row['class'] == 1 else 'Failure'}"
    ).add_to(launch_outcomes_map)

# Display the map
launch_outcomes_map

In [ ]:
spacex_df.tail(10)

     Launch Site        Lat       Long  class
46    KSC LC-39A  28.573255 -80.646895      1
47    KSC LC-39A  28.573255 -80.646895      1
48    KSC LC-39A  28.573255 -80.646895      1
49  CCAFS SLC-40  28.563197 -80.576820      1
50  CCAFS SLC-40  28.563197 -80.576820      1
51  CCAFS SLC-40  28.563197 -80.576820      0
52  CCAFS SLC-40  28.563197 -80.576820      0
53  CCAFS SLC-40  28.563197 -80.576820      0
54  CCAFS SLC-40  28.563197 -80.576820      1
55  CCAFS SLC-40  28.563197 -80.576820      0

In [ ]:
marker_cluster = MarkerCluster()

In [ ]:

# Apply a function to check the value of `class` column
# If class=1, marker_color value will be green
# If class=0, marker_color value will be red

In [ ]:
# Add marker_cluster to current site_map
site_map.add_child(marker_cluster)

# for each row in spacex_df data frame
# create a Marker object with its coordinate
# and customize the Marker's icon property to indicate if this launch was successed or failed,
# e.g., icon=folium.Icon(color='white', icon_color=row['marker_color']
for index, record in spacex_df.iterrows():
    # TODO: Create and add a Marker cluster to the site map
    # marker = folium.Marker(...)
    marker_cluster.add_child(marker)

site_map

In [ ]:
# TASK 3: Calculate the distances between a launch site to its proximities

In [ ]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

In [ ]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

In [ ]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

In [ ]:
# find coordinate of the closet coastline
# e.g.,: Lat: 28.56367  Lon: -80.57163
# distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)

### Calculate the distance from a launch site to a coastline

Let's choose the first launch site, 'CCAFS LC-40', from `launch_sites_df` and a sample coastline point to calculate the distance. We will then visualize this on the `site_map`.

In [ ]:
# Select a launch site (e.g., the first one in launch_sites_df)
launch_site = launch_sites_df.loc[0]
launch_site_lat = launch_site['Lat']
launch_site_lon = launch_site['Long']

# Sample coastline coordinate (from the example in the prompt)
coastline_lat = 28.56367
coastline_lon = -80.57163

# Calculate the distance to the coastline
distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)
print(f"Distance from {launch_site['Launch Site']} to coastline: {distance_coastline:.2f} km")

# Add a marker for the coastline point
folium.Marker(
    [coastline_lat, coastline_lon],
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#0000FF;"><b>Coastline</b></div>',
    )
).add_to(site_map)

# Draw a line between the launch site and the coastline
points = [[launch_site_lat, launch_site_lon], [coastline_lat, coastline_lon]]
folium.PolyLine(points, color='blue', weight=2.5, opacity=1).add_to(site_map)

# Display the map with the new additions
site_map

Distance from CCAFS LC-40 to coastline: 0.58 km

In [ ]:
# Create and add a folium.Marker on your selected closest coastline point on the map
# Display the distance between coastline point and launch site using the icon property
# for example
distance_marker = folium.Marker(
   [coastline_lat, coastline_lon],
   icon=DivIcon(
       icon_size=(20,20),
       icon_anchor=(0,0),
       html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance_coastline),
       )
   )
site_map.add_child(distance_marker)
site_map

In [ ]:
# Create a `folium.PolyLine` object using the coastline coordinates and launch site coordinate
lines = folium.PolyLine(locations=points, weight=1)
site_map.add_child(lines)

### Calculate distances to other proximities (city, railway, highway)

In [ ]:
# Sample coordinates for a city, railway, and highway near CCAFS LC-40
# These are illustrative coordinates and might not be exact real-world locations
city_lat, city_lon = 28.61200, -80.80770 # Example: Titusville, FL
railway_lat, railway_lon = 28.56300, -80.57560 # Example: Near Cape Canaveral rail line
highway_lat, highway_lon = 28.56270, -80.57060 # Example: Near FL-401

# Calculate distances
distance_city = calculate_distance(launch_site_lat, launch_site_lon, city_lat, city_lon)
distance_railway = calculate_distance(launch_site_lat, launch_site_lon, railway_lat, railway_lon)
distance_highway = calculate_distance(launch_site_lat, launch_site_lon, highway_lat, highway_lon)

print(f"Distance from {launch_site['Launch Site']} to City: {distance_city:.2f} km")
print(f"Distance from {launch_site['Launch Site']} to Railway: {distance_railway:.2f} km")
print(f"Distance from {launch_site['Launch Site']} to Highway: {distance_highway:.2f} km")

# Function to add a marker with distance and draw a line
def add_distance_marker_and_line(map_obj, start_lat, start_lon, end_lat, end_lon, distance, label, line_color='green', marker_color='#d35400'):
    # Add marker for the end point
    folium.Marker(
        [end_lat, end_lon],
        icon=DivIcon(
            icon_size=(20,20),
            icon_anchor=(0,0),
            html=f'<div style="font-size: 12; color:{marker_color};"><b>{label}: {distance:.2f} KM</b></div>',
        )
    ).add_to(map_obj)

    # Draw a line between the launch site and the end point
    points = [[start_lat, start_lon], [end_lat, end_lon]]
    folium.PolyLine(points, color=line_color, weight=2.5, opacity=1).add_to(map_obj)

# Add markers and lines for City, Railway, and Highway
add_distance_marker_and_line(site_map, launch_site_lat, launch_site_lon, city_lat, city_lon, distance_city, 'City', line_color='purple')
add_distance_marker_and_line(site_map, launch_site_lat, launch_site_lon, railway_lat, railway_lon, distance_railway, 'Railway', line_color='orange')
add_distance_marker_and_line(site_map, launch_site_lat, launch_site_lon, highway_lat, highway_lon, distance_highway, 'Highway', line_color='red')

# Display the updated map
site_map

Distance from CCAFS LC-40 to City: 23.17 km
Distance from CCAFS LC-40 to Railway: 0.19 km
Distance from CCAFS LC-40 to Highway: 0.66 km

Now that we have a distance calculation function, we need to choose a launch site and some proximity points to measure distances to. Let's start with one of the launch sites from `launch_sites_df`.